### ISSUE TITLE
The video is just stop

### ISSUE THREAD

**Issue by koteiyt** [Assasans/found-footage#11]
while playing the video, it stops abruptly, I attach the logs
[LogOutput.log](https://github.com/Assasans/found-footage/files/14970567/LogOutput.log)

**Comment by koteiyt** [comment]
host is my friend

**Comment by koteiyt** [comment]
?

**Comment by Assasans** [comment]
The log seems normal, there are no exceptions during video playback. I can't test this right now, try temporarily disabling all other mods and see if the bug persists, if so, upload the log. Same problem in #8.

**Comment by koteiyt** [comment]
okay,i try

**Comment by koteiyt** [comment]
And also, my friend was fine, I was playing with him

**Comment by koteiyt** [comment]
When I'm alone and without mods, everything works

**Comment by koteiyt** [comment]
i'l try with mods

**Comment by koteiyt** [comment]
it works with mods too lol

**Comment by koteiyt** [comment]
i try later with my friend

**Comment by koteiyt** [comment]
when i play with friend it frezzes

**Comment by Assasans** [comment]
Should be fixed in v0.2.2.

**Comment by Assasans** [comment]
Closed due to inactivity, please reopen if the issue is not resolved.
