### ISSUE TITLE
Extraction Fail

### ISSUE THREAD

**Issue by Rlntor** [Assasans/found-footage#12]
What i tried: 
Using only Found footage mod;
Changing url to https://foundfootage-server.assasans.dev ;
Reinstalling game and mods - my thoughts was "maybe its problem from my side"

I was able to extract recording only once, when i used vpn, but it was on other url. But of course vpn is not a good solution for this.
I really like the idea of this mod, so i hope this can help a little bit to fix this.

There is a lot of "Spawned found camera" in log, i think its because spawnrate set to 1, so i can find camera faster and test if mod is working for me.
Also i after reading log i found "404 not found" error when footage was downloading i think. Idk maybe its important 
![image](https://github.com/Assasans/found-footage/assets/167010548/54112d72-58e6-4b2f-a94d-43638cb0ca6b)

[LogOutput.log](https://github.com/Assasans/found-footage/files/14971097/LogOutput.log)

**Comment by Assasans** [comment]
That's strange, the mod can't even get the version from the server, so it's definitely not a random broken video error.
> [Info   :   Console] An error occurred while fetching version: 404 (Not Found)
> [Error  :Found Footage] Local version 0.2.1 is NOT compatible with remote 0.0.0 (incompatible)

Open https://foundfootage-server.assasans.dev/version in your browser and verify that the issuer of the SSL certificate is `C=US; O=Let's Encrypt; CN=E1`. Have you installed any root certificates from your ISP / government?

**Comment by Rlntor** [comment]
In certificate all same as you said, C=US, CN=E1, O=Let's Encrypt.
Dont really know what is "root certificate" but after some research i dont think i ever downloaded something like that

**Comment by Rlntor** [comment]
Ok i think i get it to work.
The issue was: im blind as hell.

In confige was https://foundfootage-server.assasans.dev/version 
Not the https://foundfootage-server.assasans.dev

After changing to this, when i grabed camera console started spaming about CreateFakeVideo, so i already thought mod is working, then i got CD and successfully watched video of random dude. 

Awesome mod and misstake from my side. 👍

**Comment by Rlntor** [comment]
Everything works, just one small mistake can break everything so if someone also made same misstake i hope they would see this
