### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by deman6545** [Assasans/found-footage#13]
I had this with a few other mods but everything worked. As soon as I extracted the video my game froze, said content warning was loading and then it just crashed entirely. Hope this can help in the developement as I know that it is still experimental. The person I was playing with said he didn't crash, so I have no idea what is going on

**Comment by Assasans** [comment]
Do you have a log of when the game crashed (`BepInEx/LogOutput.log`)?

**Comment by deman6545** [comment]
> Do you have a log of when the game crashed (`BepInEx/LogOutput.log`)?
 
No because it killed my game and my command prompt. If you have a way i can get one I will gladly get it for you.

**Comment by Assasans** [comment]
It is written on fly, so it should contain at least something even if the process is killed. So if you will encounter freeze second time, send logs too.
