### ISSUE TITLE
Failed to get video path error

### ISSUE THREAD

**Issue by Shadodix** [Assasans/found-footage#17]
It fails to get the video path when you try to play the file, I looked into it and saw that it tried to open a file called fullRecording.webm when the file in the folder was output.webm
I am on windows 11 if that helps..
![image_2024-04-27_012012464](https://github.com/Assasans/found-footage/assets/168266102/617bf098-781f-4ef4-a48b-7fd07d122fc8)
![image_2024-04-27_012042771](https://github.com/Assasans/found-footage/assets/168266102/4dfe3d7d-c387-4759-8188-4368fd064160)

**Comment by Assasans** [comment]
Possibly same issue as #14. Do you have any other mods installed? I have never encountered this in a vanilla game.

**Comment by Shadodix** [comment]
> Possibly same issue as #14. Do you have any other mods installed? I have never encountered this in a vanilla game.

After looking at that I found the issue, its a mod called MoreCameras I believe. thanks for the help!

**Comment by Assasans** [comment]
Found the problem, I was not calling `Clip.SetValid(true)` on fake clip, so MoreCameras just skipped processing those recordings. Will be fixed in next release.
