### ISSUE TITLE
Suggestion: Save UserId and WarningShown outside of config folder

### ISSUE THREAD

**Issue by RuiNtD** [Assasans/found-footage#18]
The `UserId` and `WarningShown` options should be saved outside the config folder, so they don't get reset when importing into r2modman / Thunderstore App, and so they don't get shared with other users when exporting with r2modman / Thunderstore App.

**Comment by Assasans** [comment]
I thought about it, but not sure if it is ok for mod to write outside config directory. I guess `AppData/Roaming/Landfall/Content Warning/MOD_GUID.cfg` would be good for persistent configs (although by default there is no `Landfall/Content Warning` directory).

**Comment by Assasans** [comment]
Implemented in b0cdd5d, available in v0.3.1.

**Comment by RuiNtD** [comment]
If you wanted to use it, the game actually saves to `%USERPROFILE%\AppData\LocalLow\Landfall Games\Content Warning`

**Comment by RuiNtD** [comment]
Seems like you would have to actually save the data outside the BepInEx folder. The files are still included in r2modman / Thunderstore exports.
![7zFM_ksIDT3dPfX](https://github.com/Assasans/found-footage/assets/1149870/4ea4a9e0-6f34-49af-8663-dd3582798a28)

**Comment by RuiNtD** [comment]
Hello?
