### ISSUE TITLE
Camera video extraction failed

### ISSUE THREAD

**Issue by rosesxirosie** [Assasans/found-footage#2]
Cameras can be found on the map, but each camera has 100% memory and extraction fails every time 😭

**Comment by Assasans** [comment]
Are you playing multiplayer? I have encountered the "extraction failed" error only when some players do not have the mod installer (the game does the extraction on each client separately, and clients without the mod have no found recording data).

> each camera has 100% memory

Fixed in recent commit, will be in new release soon.

**Comment by rosesxirosie** [comment]
Thank you for your hard work. The camera memory issue has been resolved, but my friend and I tested it and found that the camera still failed to extract even though both of us had installed mod.
[LogOutput.log]

**Comment by rosesxirosie** [comment]
[LogOutput.log](https://github.com/Assasans/found-footage/files/14954978/LogOutput.log)

**Comment by rosesxirosie** [comment]
Thank you for your hard work. The camera memory issue has been resolved, but my friend and I tested it and found that the camera still failed to extract even though both of us had installed mod.
[LogOutput.log](https://github.com/Assasans/found-footage/files/14954982/LogOutput.log)

**Comment by Assasans** [comment]
> [Info   :   Console] An error occurred while fetching version: An error occurred while sending the request
> [Error  :Found Footage] Local version 0.2.1 is NOT compatible with remote 0.0.0 (incompatible)
> [Info   :   Console] An error occurred while downloading the file: An error occurred while sending the request

It looks like you have the same problem as in #5, the mod cannot access the server due to Cloudflare Workers possibly being blocked by your ISP.
Can you access https://foundfootage-server.assasans.workers.dev/version from a browser? If not, does https://assasans.araumi.org work? I could do a reverse proxy through this host.

**Comment by rosesxirosie** [comment]
If VPN is not enabled, the link cannot be accessed, but the second link can be accessed normally.

**Comment by Pedroisbanana** [comment]
> > [Info   :   Console] An error occurred while fetching version: An error occurred while sending the request
> > [Error  :Found Footage] Local version 0.2.1 is NOT compatible with remote 0.0.0 (incompatible)
> > [Info   :   Console] An error occurred while downloading the file: An error occurred while sending the request
> 
> It looks like you have the same problem as in #5, the mod cannot access the server due to Cloudflare Workers possibly being blocked by your ISP. Can you access https://foundfootage-server.assasans.workers.dev/version from a browser? If not, does https://assasans.araumi.org work? I could do a reverse proxy through this host.

I can access the second link wthout any issues

**Comment by Assasans** [comment]
Try opening https://foundfootage-server.assasans.dev/version in a browser, this should work as it is no longer a `*.workers.dev` domain. If so, set `ServerUrl = https://foundfootage-server.assasans.dev` in the mod's config file.

**Comment by rosesxirosie** [comment]
Thank you very much, all the problems were solved!
