### ISSUE TITLE
failed to extract

### ISSUE THREAD

**Issue by DiViMii** [Assasans/found-footage#20]
[LogOutput.log](https://github.com/Assasans/found-footage/files/15171236/LogOutput.log)

**Comment by Assasans** [comment]
> ```
> Parameter name: string
>   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_string_from_byvalstr(intptr,int)
>   at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal.PtrToStructure(intptr,System.Type)
>   at System.Runtime.InteropServices.Marshal.PtrToStructure[T] (System.IntPtr ptr)
>   at System.Net.NetworkInformation.Win32NetworkInterface.get_FixedInfo ()
>   at System.Net.NetworkInformation.Win32IPGlobalProperties.get_DomainName ()
>   at System.Net.CookieContainer..ctor ()
>   at System.Net.Http.MonoWebRequestHandler.get_CookieContainer ()
>   at System.Net.Http.MonoWebRequestHandler.CreateWebRequest (System.Net.Http.HttpRequestMessage request)
>   at System.Net.Http.MonoWebRequestHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
>   at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken)
>   at FoundFootage.VersionChecker.GetVersion ()
> ```

Seems like this issue: https://forum.unity.com/threads/httpclient-getasync-doesnt-work-on-computers-with-pc-names-that-contain-non-latin-characters.1561297/
I will switch to `UnityWebRequest` in the next version and hope that it is not as crappy as its FCL version.
