### ISSUE TITLE
how the heck do i get views for lost footage. I know its not really a bug but im sorry I just need help 

### ISSUE THREAD

**Issue by Beangina459** [Assasans/found-footage#21]

**Comment by Assasans** [comment]
Implemented in a444f33, available in v0.4.0, use `FoundVideoScoreMultiplier` to change score multiplier.

**Comment by Beangina459** [comment]
I don't know what the hell I'm doing can you explain it in more basic terms please

**Comment by Assasans** [comment]
Most of the videos you find will get you views (x0.5 by default) if you use v0.4.0 or newer. Some videos that were uploaded on older versions don't have views data and won't give views.
