### ISSUE TITLE
Weird sudden bug

### ISSUE THREAD

**Issue by ImCryingAboutIt** [Assasans/found-footage#27]
Yesterday everything was working fine. Now for some reason when launching any save file the day automatically ends and extra camera spawns nearby from original one, when picking up this camera the entire inventory breaks. These extra cameras can spawn infinitely on every progressed day apparently. No mod that might be conflicting with this one were added since last stable session.

**Comment by Assasans** [comment]
Oh, I forgot to comment out the code that I use to test cameras. It was added in 0d715ee (v0.4.2). You can downgrade to v0.4.1 for now, I'll release a fix today.

**Comment by ImCryingAboutIt** [comment]
alright, thanks for answering.
