### ISSUE TITLE
error

### ISSUE THREAD

**Issue by superstrongbozo** [Assasans/found-footage#3]
![image](https://github.com/Assasans/found-footage/assets/166734896/4d6b20b6-79ff-4a71-942b-34a53378f524)
how should i fix that????

**Comment by Assasans** [comment]
This error means that the mod cannot access the server where the videos are stored.
Do you have `ServerUrl = https://foundfootage-server.assasans.workers.dev` in a configuration file at `BepInEx/config/jp.assasans.cw.FoundFootage.cfg`?
Can you access https://foundfootage-server.assasans.workers.dev/version from a browser? If so, can you upload the log file located at `BepInEx/LogOutput.log`?

**Comment by superstrongbozo** [comment]
you mean that the only way i can play with this mod is turn on my vpn?

**Comment by superstrongbozo** [comment]
because i have ServerUrl = https://foundfootage-server.assasans.workers.dev in the config file

**Comment by Assasans** [comment]
You have the same problem as #2 and #5.
Try opening https://foundfootage-server.assasans.dev/version in a browser, this should work as it is no longer a `*.workers.dev` domain. If so, set `ServerUrl = https://foundfootage-server.assasans.dev` in the mod's config file.

**Comment by superstrongbozo** [comment]
thank you so much bro, it works
