### ISSUE TITLE
Video extraction fails every time

### ISSUE THREAD

**Issue by Pedroisbanana** [Assasans/found-footage#5]
Everybody in the team had this mod installed, everybody has been getting this same popup:
![image](https://github.com/Assasans/found-footage/assets/125575510/e0618fa2-2182-48aa-a960-45e54051d25a)
Server url that I have in cfg: https://foundfootage-server.assasans.workers.dev
I cannot access that link without vpn, perhaps that's the issue

**Comment by z33r0x** [comment]
Yeah, DPI blocks this link for me too, I used goodbyedpi to fix https://github.com/ValdikSS/GoodbyeDPI

**Comment by Pedroisbanana** [comment]
Me forgor the log 💀
[LogOutput.log](https://github.com/Assasans/found-footage/files/14950917/LogOutput.log)

**Comment by Assasans** [comment]
Try opening https://foundfootage-server.assasans.dev/version in a browser, this should work as it is no longer a `*.workers.dev` domain. If so, set `ServerUrl = https://foundfootage-server.assasans.dev` in the mod's config file.

**Comment by Pedroisbanana** [comment]
> Try opening https://foundfootage-server.assasans.dev/version in a browser, this should work as it is no longer a `*.workers.dev` domain. If so, set `ServerUrl = https://foundfootage-server.assasans.dev` in the mod's config file.

Works now, thank you for such an amazing mod
