### ISSUE TITLE
Extraction Fail 'Singleplayer'

### ISSUE THREAD

**Issue by TheScarlettRose2501** [Assasans/found-footage#6]
Line 1075: 
[LogOutput.log](https://github.com/Assasans/found-footage/files/14950084/LogOutput.log)

Found camera outside the bell, brought it back and the extraction failed despite being the only one playing.
Side note: When playing with a group the previous day it still didn't work, but my own recording did work.

**Comment by Assasans** [comment]
I haven't found any `InitCamera` log messages from `VideoCamera.ConfigItem` (responsible for downloading video from the server), so it's most likely a patching problem.
There also was an error:
> ```cs
> [Error  :  HarmonyX] Failed to patch virtual void VideoCamera::ConfigItem(ItemInstanceData data, Photon.Pun.PhotonView playerView): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>   ...
>   at Flashcard.Patches.VideoCameraPatch.UpdateFilmAmount (System.Collections.Generic.IEnumerable`1[T] instructions) [0x00000] in ./Patches/VideoCameraPatch.cs:14 
> ```

So I guess my mod and Flashcard are conflicting between each other. I have Flashcard installed and there are no errors, but my version is v0.2.0 and yours is v0.3.2.
Try temporarily disabling Flashcard and see if the extraction error persists. If this is the case, I'll try to release a fix tomorrow.

**Comment by TheScarlettRose2501** [comment]
It did seem to be Flashcard that was causing the error. Seems to work fine without it enabled.

**Comment by Assasans** [comment]
I have checked and it is Infinite Camera and Flashcard that are conflicting with each other. Flashcard searches for `Ldc_R4` with `90f` operand, while Infinite Camera has already changed this to `float.MaxValue`.
If I keep either Flashcard or Infinite Camera - Found Footage works.
