### ISSUE TITLE
Video is playing for few seconds only

### ISSUE THREAD

**Issue by plechovka** [Assasans/found-footage#8]
As the title say, only the host can see the whole clip while other people in lobby can see few seconds before it cuts and no longer works.

**Comment by Assasans** [comment]
Can you send a game log located at `BepInEx/LogOutput.log` when the video freezes.
I had this problem when the video was not generating comments. I'm patching this method, but MoreComments seems to conflict with it, causing it not to generate comments again.

**Comment by Assasans** [comment]
There seems to be a problem with transmitting video through Mycelium. When I play video through `ffplay`, I get a bunch of errors:
> Element at 0x8027f ending at 0x1efe24 exceeds containing master element ending at 0xa506f
> [matroska,webm @ 00000222e5486440] Length 5 indicated by an EBML number's first byte 0x0f at pos 657250 (0xa0762) exceeds max length 4.
> [matroska,webm @ 00000222e5486440] File ended prematurely

**Comment by plechovka** [comment]
So it would be working in next update?
Basically when it won't be v0.2.1 anymore in thunderstore?

**Comment by Assasans** [comment]
Yeah, I'll check again today to see if it works in multiplayer and release a new version.

**Comment by Assasans** [comment]
Published v0.2.2 on Thunderstore, should be fixed now.

**Comment by FireFlower45YT** [comment]
You may want to close this thread

**Comment by Assasans** [comment]
Closed due to inactivity, please reopen if the issue is not resolved.
